### PR TITLE
Add new feature to create yaml including jenkins core and plugins and give users a choice to choose

### PR DESCRIPTION
**Pull request by jxr98**
**Make sure that you've checked the boxes below before you submit PR:**

### Always

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Written well with PR title, we generate the [release notes](https://github.com/jenkins-zh/jenkins-cli/releases) base on that

### For the bug fixes or features only

- [ ] [Quality Gate Passed](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli). Change this URL to your PR.
- [ ] The coverage is xxx on the new lines
- [ ] I've tested it by manual in the following platform
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- [ ] Unit Test covered
- [ ] e2e Test covered

### CODE REVIEW

**Comment by jxr98** [comment]
The center_list and plugin_center are also included in the other two prs, but I need to use some of the functions and struct type defined in those two files. Maybe we can review the other two prs first.

**Comment by LinuxSuRen** [comment]
> The center_list and plugin_center are also included in the other two prs, but I need to use some of the functions and struct type defined in those two files. Maybe we can review the other two prs first.

Can you point which two PRs?

**Comment by jxr98** [comment]
> > The center_list and plugin_center are also included in the other two prs, but I need to use some of the functions and struct type defined in those two files. Maybe we can review the other two prs first.
> 
> Can you point which two PRs?

One has been merged and the other is https://github.com/jenkins-zh/jenkins-cli/pull/611.

**Comment by jxr98** [comment]
Try this command `./jcli upgrade labmouse`  and a docker installed local or remotely with the Docker Daemon exposed with a port. The default is 127.0.0.1:2375. For example, if you have Docker available in 209.23.56.59 with the Docker Daemon exposed with -H tcp://0.0.0.0:8888, please add `--ip 209.23.56.59 --docker-port 8888` to the command. 
This command is going to prompt your choose what you want to upgrade and start jenkins with the upgraded and 'unupgraded' plugins in a docker container and conduct an API test.

**Review by LinuxSuRen — APPROVED** [review]

**Pull request merged**
