### PR TITLE
Add new feature to backup jenkins relying on thinBackup plugin

### PR DESCRIPTION
**Pull request by jxr98**
**Make sure that you've checked the boxes below before you submit PR:**

### Always

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Written well with PR title, we generate the [release notes](https://github.com/jenkins-zh/jenkins-cli/releases) base on that

### For the bug fixes or features only

- [ ] [Quality Gate Passed](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli). Change this URL to your PR.
- [ ] The coverage is xxx on the new lines
- [ ] I've tested it by manual in the following platform
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- [ ] Unit Test covered
- [ ] e2e Test covered

### CODE REVIEW

**Comment by jxr98** [comment]
This function backs up global and job specific configurations relying on thinBackup plugin. I found an url which can trigger thinBackup to backup, but it doesn't return any message. Thus, jcli cannot handle errors which may happen and cannot make sure that the backup succeeded. I figured out a solution which is the --check flag. If jcli can access the backup directory set in thinBackup plugin, '--check true' is recommended to be parsed to backup command and then jcli will check if a new directory which follows a name pattern is created.

**Comment by LinuxSuRen** [comment]
still working on this PR?

**Comment by jxr98** [comment]
> still working on this PR?

I think it is done for now and I created a pull request in thinBackup plugin repository. The pr is waiting to be reviewed. Now this backup function can not check if backup succeeds in remote computer.

**Comment by LinuxSuRen** [comment]
> I think it is done for now

WIP means working in progress

**Review by LinuxSuRen — APPROVED** [review]

**Pull request merged**
