### PR TITLE
Add fish completion support

### PR DESCRIPTION
**Pull request by sikmir**
**Make sure that you've checked the boxes below before you submit PR:**

### Always

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Written well with PR title, we generate the [release notes](https://github.com/jenkins-zh/jenkins-cli/releases) base on that

### For the bug fixes or features only

- [ ] [Quality Gate Passed](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli). Change this URL to your PR.
- [ ] The coverage is xxx on the new lines
- [x] I've tested it by manual in the following platform
  - [x] MacOS
  - [ ] Linux
  - [ ] Windows
- [x] Unit Test covered
- [x] e2e Test covered

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
There are some errors that need to be fixed. I will do it due to it is not caused by this PR. And thanks for your time.

**Comment by LinuxSuRen** [comment]
I removed some outdated config and tests. https://github.com/jenkins-zh/jenkins-cli/pull/773

**Comment by sikmir** [comment]
> I removed some outdated config and tests. #773
> 
> hi @sikmir , please update your branch from the master branch. Thanks.

Updated, but still failing.

**Comment by sikmir** [comment]
@LinuxSuRen build is OK now

**Review by LinuxSuRen — APPROVED** [review]

**Pull request merged**
