### PR TITLE
Add MacPorts Documentation

### PR DESCRIPTION
**Pull request by harens**
**Make sure that you've checked the boxes below before you submit PR:**

Closes https://github.com/jenkins-zh/jenkins-cli/issues/402.

For MacPorts, I included how to get shell completion and noted the project page.

I also changed Mac --> [macOS](https://en.wikipedia.org/wiki/MacOS) and added a repology badge. Finally, I changed the Linux instructions syntax highlighting from `text` to `sh`.

### Always

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Written well with PR title, we generate the [release notes](https://github.com/jenkins-zh/jenkins-cli/releases) base on that

### For the bug fixes or features only

- [ ] [Quality Gate Passed](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli). Change this URL to your PR.
- [ ] The coverage is xxx on the new lines
- [ ] I've tested it by manual in the following platform
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows

### CODE REVIEW

**Comment by harens** [comment]
Thanks @LinuxSuRen. Great automation with the bot btw.

**Comment by LinuxSuRen** [comment]
Automation bot is helpful and useful.

**Pull request merged**
